# Generated by Django 5.1.5 on 2025-01-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_twiliocredentials_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twiliocredentials',
            name='account_sid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='twiliocredentials',
            name='auth_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='twiliocredentials',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
